#!/usr/bin/env zsh

cook "Work on next task in plan.md. When it is complete, mark it as complete. git commit after every task with a useful message about what has been done and how." ralph 5 "DONE if all tasks complete, else NEXT"

# Option 2
# cook "Work on next task in plan.md" \
#   review "Code review" "DONE if no High issues, else ITERATE" \
#   ralph 5 "DONE if all tasks complete, else NEXT"