#!/usr/bin/env zsh

cook "Redesign the website using the design brief in './example-design/research.md', aim for a super modern, up to date design with a friendly but professional vibe and a 'wow' factor." \
  v3 "The best design, most modern looking with the design brief followed" \
  --yes
