#!/usr/bin/env zsh


cook "Work on next task in plan.md. When it is complete, mark it as complete. git commit and push after every task with a useful message about what has been done and how." \
  ralph 5 "DONE if all tasks complete, else NEXT" \
  --yes



# cook "Work on next task in plan.md. When it is complete, mark it as complete. git commit and push after every task with a useful message about what has been done and how." \
#   ralph 5 "DONE if all tasks complete, else NEXT" \
#   --yes --model sonnet
