#!/usr/bin/env zsh

PROMPT="
Redesign the website using the design brief in './example-design/research.md'.
Aim for a super modern, up to date design.
With a friendly but professional vibe and a 'wow' factor.
"

cook "$PROMPT" \
  v3 "The best design, most modern looking, with the design brief followed" \
  --yes
