services:
  build:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build"

  base:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install"

  dev:
    extends:
      service: base
    ports:
      - 8080:8080
    command: sh -c "npm install && node --no-deprecation src/watch.js & node --no-deprecation src/server.js & wait"

  serve:
    image: joseluisq/static-web-server:2-alpine
    network_mode: host
    restart: unless-stopped
    environment:
      - SERVER_ROOT=/var/public
      - SERVER_HOST=::1
      - SERVER_PORT=8080
      - SERVER_HEALTH=true
    depends_on:
      build:
        condition: service_completed_successfully
    volumes:
      - ./public:/var/public
    healthcheck:
      test: 'nc -z localhost 8080 || exit 1'
      interval: 10s
      timeout: 5s
      retries: 5
