version: 2.1

orbs:
  node: circleci/node@4.7
  gh-pages: sugarshin/gh-pages@1.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Format Check
          command: npm start format.check
      - run:
          name: Lint Check
          command: npm start lint.check
      - run:
          name: Build www
          command: npm start build

workflows:
  publish:
    jobs:
      - build-and-test
