#!/usr/bin/env zsh

convert -density 512x512 -background transparent favicon.svg -define icon:auto-resize -colors 256 favicon.ico
convert -density 512x512 -background transparent favicon.svg -resize 180x180 apple-touch-icon.png
convert -density 512x512 -background transparent favicon.svg -resize 512x512 favicon.png